//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reservation_booking_system.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ContactNumber { get; set; }
        public string Email { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string CreatedTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string UpdatedTime { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remarks { get; set; }
        public string HashKey { get; set; }
        public string HashedPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
    }
}
