//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reservation_booking_system.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string FromTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string CreatedTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string UpdatedTime { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remarks { get; set; }
        public string Description { get; set; }
        public string EventID { get; set; }
        public string Approval { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Admin Admin { get; set; }
    }
}
